# HYPRIDLE CONFIGURATION

general {
    # lock_cmd: Runs when loginctl lock-session is called
    lock_cmd = omarchy-lock-screen                         
    
    # before_sleep_cmd: Ensures the session is locked before the system suspends
    before_sleep_cmd = loginctl lock-session               
    
    # after_sleep_cmd: Gives NVIDIA/DPMS a 2s head start on wake-up to prevent black screens
    after_sleep_cmd = sleep 2 && hyprctl dispatch dpms on  
    
    # wait 3 seconds for the lock script to finish before allowing the suspend to proceed
    inhibit_sleep = 3                                      
}

# 1. Start screensaver (2.5 min)
listener {
    timeout = 150                                             
    on-timeout = pidof hyprlock || omarchy-launch-screensaver 
}

# 2. Lock the session (10 min)
listener {
    timeout = 600                      
    on-timeout = loginctl lock-session 
}

# 3. Keyboard Backlight Off (10.5 min)
listener {
    timeout = 630                                            
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  
    on-resume = brightnessctl -rd '*::kbd_backlight'         
}

# 4. Monitors Off (10.5 min)
listener {
    timeout = 630                                            
    on-timeout = hyprctl dispatch dpms off                   
    on-resume = hyprctl dispatch dpms on && brightnessctl -r 
}

# 5. FULL SYSTEM SUSPEND (15 min)
listener {
    timeout = 900                                
    on-timeout = systemctl suspend                
}